# Generated by Django 3.0.8 on 2020-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('marks', models.FloatField()),
                ('pw', models.CharField(max_length=10)),
            ],
        ),
    ]
