# Generated by Django 3.0.8 on 2020-08-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
                ('caddr', models.CharField(max_length=50)),
                ('cemail', models.EmailField(max_length=254)),
                ('cphone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AllOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('batch_no', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('seller', models.CharField(choices=[('Flipkart', 'Flipkart'), ('Amazon', 'Amazon'), ('Ebay', 'Ebay'), ('Ajio', 'Ajio')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.Customer')),
            ],
        ),
    ]
