# Generated by Django 3.1.2 on 2020-10-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artiicle',
            new_name='Article',
        ),
    ]
